export type SacredRepairRitual = {
  title: string;
  lineage: string;
  duration: string;
  intention: string;
  setup: string;
  steps: string[];
  teaching: string;
};

export type SacredRepairChapter = {
  id: string;
  title: string;
  partLabel: string;
  emotionalFrame: string;
  rituals: SacredRepairRitual[];
};

const emotionalFrameByChapter: Record<string, string> = {
  "touch-massage-sacred-spot": "Repair through reverent touch",
  "embrace-embodied-connection": "Repair through holding and nervous-system settling",
  "sacred-union-rituals": "Repair through conscious lovemaking",
  "emotional-clearing-authentic-relating": "Repair through truth and emotional honesty",
};

export const SACRED_REPAIR_CHAPTERS: SacredRepairChapter[] = 
[
  {
    id: "touch-massage-sacred-spot",
    title: "Touch, Massage & Sacred Spot",
    partLabel: "Part III",
    emotionalFrame: emotionalFrameByChapter["touch-massage-sacred-spot"],
    rituals: [
      {
        title: "The Yoga of Touch",
        lineage: "Daniel Odier · Kashmir Shaivism · Spanda lineage",
        duration: "30 minutes or longer",
        intention: "To discover that touch is a form of yoga — and that the body, received with full presence, reveals its nature as vibration (spanda) and consciousness, not as flesh separate from the cosmos.",
        setup: "Warm room, candles, no music. Receiver lies naked or lightly covered on a comfortable surface. Giver begins seated beside them.",
        steps: [
          "The giver first sits in stillness for two minutes, hands on their own heart, until the hands feel warm and awake.",
          "First touch: place one palm lightly on the receiver's lower belly, the other at the top of the chest. Hold for several breaths. No movement.",
          "Begin to move one hand at a time, incredibly slowly — so slow that the receiver cannot quite track when movement begins and ends.",
          "The hand does not massage. It listens. It pauses wherever the body seems to call it.",
          "If emotion arises in the receiver, the giver does not rush to comfort — simply stays, breath steady, contact unbroken.",
          "End by withdrawing the hands even more slowly than they arrived. Sit beside the receiver in silence until they open their eyes.",
        ],
        teaching: "Odier received this transmission from the yogini Lalita Devi. In his teaching, the hand is not an instrument; it becomes a window through which the whole cosmos touches the beloved.",
      },
      {
        title: "Sacred Spot Massage — Yoni Ritual",
        lineage: "Charles & Caroline Muir · Source School of Tantra Yoga",
        duration: "60–90 minutes (the full ceremony)",
        intention: "To heal old wounds held in the feminine body and awaken her capacity for deep pleasure and emotional release.",
        setup: "A bath for her first; she bathes while he prepares the room — flowers, candles, fresh sheets, water and fruit beside the bed. Towels and warmed oil ready.",
        steps: [
          "He greets her as she enters, sitting in Namaste, offering two sentences of praise and intention.",
          "Begin with a full body massage — shoulders, back, legs, belly — nothing hurried, no destination.",
          "When she is ready, she turns onto her back, a pillow under her hips. External yoni massage with warm oil: circles around the outer labia, the mound, the thighs.",
          "Internal contact only when she invites it. One finger, well-lubricated, enters slowly. He curls upward toward the front wall — the sacred spot.",
          "Hold still. Listen. If emotion comes — grief, rage, laughter, pleasure, tears — he breathes with her, stays present, says nothing unless she asks.",
          "The massage ends when she says so. Not before. He withdraws as slowly as he entered. He holds her until she is fully back.",
        ],
        teaching: "Muir's central teaching: the goal is not orgasm. The goal is presence. Orgasm, when it arrives, is a side effect of total safety — and often what arrives first is not pleasure but the release of everything the yoni has been holding.",
      },
      {
        title: "Sacred Spot Massage — Lingam Ritual",
        lineage: "Charles & Caroline Muir · Source School of Tantra Yoga",
        duration: "45–75 minutes",
        intention: "To teach the masculine body that pleasure can be received without performing, and to decouple sexual energy from the compulsion to release.",
        setup: "He bathes first. She prepares the space with the same care described above. He lies on his back, pillow under the hips, towels underneath.",
        steps: [
          "She begins with a long, slow body massage: feet, legs, belly, chest, arms. The lingam is not touched for at least twenty minutes.",
          "Gradual awakening: warm hands on the inner thighs, the mound, the perineum — everywhere around the lingam before the lingam itself.",
          "When she touches the lingam, she does so slowly, with full breath and eye contact whenever possible.",
          "If he nears ejaculation, she stops. Waits. Let the wave recede. Each time the wave recedes, the energy rises higher in the body — this is the surf he is learning to ride.",
          "The perineum point (the 'Million-Dollar Point') can be pressed firmly at the edge of orgasm to hold the charge in.",
          "End with both hands resting, one on his heart, one on the lingam, for several minutes of stillness.",
        ],
        teaching: "The point of this practice is not denial — ejaculation can happen, or not. The point is choice. He learns that orgasmic energy can circulate through the whole body rather than being always discharged outward.",
      },
      {
        title: "Breast Massage & Nine Flower Qigong",
        lineage: "Mantak Chia · Taoist Healing Love",
        duration: "15 minutes",
        intention: "To connect the breasts with the ovaries along the Taoist life-force meridian, balance hormones, and release deep emotional and physical tension held in the heart and chest.",
        setup: "Woman seated comfortably, partner beside or behind. Hands well-warmed by rubbing together, palms open.",
        steps: [
          "Woman places her own palms over her breasts first, a moment of self-contact.",
          "Begin spiraling: small outward circles around each breast, slowly widening. Nine circles outward. Then nine inward.",
          "Move to the nipple line: spiral 'nine flowers' down from breasts toward the lower belly and groin — these are the 'flowers' along the front meridian.",
          "Pause at any spot that feels sensitive or alive. Breathe into it.",
          "Finish with the palms of both hands warming the breasts and the lower belly — one above, one below — feeling the connection between heart and womb.",
          "Rest in stillness for two minutes. The woman feels the energy; she may feel it rising unbidden to her crown.",
        ],
        teaching: "Chia teaches that feeling the energy is the whole practice. When the breasts and ovaries are in conscious conversation, the whole female endocrine system recalibrates.",
      },
      {
        title: "Testicle Massage & Scrotum Tapping",
        lineage: "Mantak Chia · Taoist Inner Alchemy",
        duration: "10 minutes",
        intention: "To wake up the foundation of male sexual energy, circulate qi through the genitals, and release stagnation caused by long sitting or chronic stress.",
        setup: "Man seated or reclining. Hands warmed. Private, relaxed, unhurried.",
        steps: [
          "Begin with the palms cupping and warming the testicles, no movement — just warmth.",
          "Gentle rolling: one testicle at a time, roll it between thumb and forefinger, feeling for any small knots. Do not squeeze.",
          "Light tapping with fingertips on the scrotum — the 'testicle tapping' practice — wakes up the nerves.",
          "Spiraling massage: small circles around each testicle, then larger circles that include the perineum.",
          "Finish by cupping and holding, then guiding the energy upward with the mind toward the navel.",
          "Rest. Feel the warm pulse. The practice is complete.",
        ],
        teaching: "Chia positions this as essential daily hygiene for men, on par with brushing teeth. When practised regularly, it keeps the entire sexual system vital, responsive, and free of stagnation.",
      },
      {
        title: "SkyDancing Tantric Massage",
        lineage: "Margot Anand · SkyDancing Tantra",
        duration: "60–90 minutes",
        intention: "To worship the beloved as god or goddess — a full-body awakening of the seven chakras through conscious, devotional touch.",
        setup: "Ritual space: flowers, candles, incense, soft music. Warmed massage oil. Receiver lies face down to begin; giver sits in meditation for five minutes first.",
        steps: [
          "Giver begins with a silent Heart Salutation (see Ritual 19). Receiver rests face down, fully relaxed.",
          "Slow, devotional strokes up the back, from sacrum to crown — each stroke one chakra at a time, with breath.",
          "As hands pass each chakra, the giver silently offers a blessing: 'May this centre be awake, free, and loved.'",
          "Turn the receiver onto their back. Continue up the front, same ritual, same blessing at each chakra.",
          "Genital honouring (optional): warm oil, reverent touch, no goal. The hands say: you are sacred.",
          "End in a Melting Hug (see Ritual 20) or quiet stillness side by side.",
        ],
        teaching: "Anand frames this as the 'art of loving' itself: giving and receiving become the same act, and what was a massage becomes a ceremony of mutual worship.",
      },
      {
        title: "The Eight Embraces & Mutual Massage",
        lineage: "Vatsyayana (attributed) · Kama Sutra",
        duration: "20–40 minutes",
        intention: "To kindle desire slowly through the classical sequence — four non-sexual embraces that generate tender longing, followed by four that carry it toward union.",
        setup: "A simple, warm space. Loose clothing. Unhurried mood.",
        steps: [
          "Begin with the four tender embraces: Sphrishtaka (a touch in passing), Viddhaka (a brush while reaching), Udghrishtaka (a slow walking embrace), Piditaka (a gentle wall-press).",
          "Move into the four passionate embraces: Lataveshtitaka (the twining creeper — she clings to him as a vine around a tree), Vrikshadhirudha (the climbing of a tree — one foot on his, one on his thigh, reaching to kiss), Tilatandula (the sesame and rice — bodies pressed so close that sesame and rice cannot be distinguished), Kshiraniraka (milk and water — full-body melting).",
          "Between each embrace, pause. Breathe. Look.",
          "Add mardana — mutual massage — at any point. Rubbing cheek to cheek, hand on hand.",
          "Let the sequence guide the mood, but Vatsyayana writes: 'when the wheel of love is once set in motion, there is then no textbook and no order.'",
          "Close wherever the embrace naturally comes to rest.",
        ],
        teaching: "The ancient text is careful: the first four embraces are for couples who 'do not yet speak freely with each other.' The whole sequence is a graduation — from first shy contact to total merging.",
      },
    ],
  },
  {
    id: "embrace-embodied-connection",
    title: "Embrace & Embodied Connection",
    partLabel: "Part IV",
    emotionalFrame: emotionalFrameByChapter["embrace-embodied-connection"],
    rituals: [
      {
        title: "The Heart Salutation",
        lineage: "Margot Anand · SkyDancing Tantra",
        duration: "3 minutes",
        intention: "To begin and end every intimate exchange with an honouring of the divinity in the other — and in oneself.",
        setup: "Stand or kneel facing each other, close enough to touch knees or foreheads.",
        steps: [
          "Bring both palms together at your own heart. Eyes closed. Breathe deeply once.",
          "Open your eyes. Slowly extend your hands forward, palms still together, then open them as if offering a gift.",
          "Touch fingertips with your partner, then palms.",
          "Fold forward slightly, forehead meeting forehead if possible, hands between your two hearts.",
          "Whisper or silently offer: 'I honour the god/goddess in you.'",
          "Rise slowly, hands returning to your own heart. Bow once more.",
        ],
        teaching: "Anand uses the Heart Salutation as the opening and closing ritual of every SkyDancing practice. The small act reframes the entire encounter: this is not a transaction; this is sacred meeting.",
      },
      {
        title: "The Melting Hug",
        lineage: "Margot Anand · SkyDancing Tantra",
        duration: "10–20 minutes (until true melting occurs)",
        intention: "To dissolve the physical and energetic boundary between two bodies and experience the full-field merging that most adults have not felt since childhood.",
        setup: "Standing, facing each other, barefoot if possible. No rush.",
        steps: [
          "Step toward each other and embrace — chest to chest, pelvis to pelvis, if both are willing.",
          "For the first minute, simply stand. Most people hold each other for five seconds and release; here you do not release.",
          "Notice the tension points: shoulders, jaw, pelvis. As each is noticed, let it soften.",
          "Synchronise the breath. Breathe into each other's chests.",
          "Somewhere between minute three and minute seven, a 'letting go' happens — a felt release where the edge between your two bodies seems to soften. This is the melt.",
          "Stay longer than you think necessary. When you do separate, do so very slowly — bodies first, hands last, eyes meeting before you step back.",
        ],
        teaching: "Anand insists the Melting Hug is not symbolic. A real biochemical event occurs — oxytocin rising, cortisol falling, nervous systems co-regulating — which is why couples who do it daily describe the change in their relationship as 'cellular.'",
      },
      {
        title: "Yab-Yum Embrace",
        lineage: "Classical Tantric Buddhism · Margot Anand · Vajrayana · SkyDancing Tantra",
        duration: "20–45 minutes",
        intention: "To enter the archetypal posture of sacred union — feminine on the lap of the masculine, hearts aligned, breath one — and let it become a living meditation.",
        setup: "The receiver (traditionally the feminine partner) sits on the lap of the giver, legs wrapped behind their back, arms around shoulders. A firm cushion helps.",
        steps: [
          "Arrange the posture slowly. Once settled, both bring hands to each other's hearts.",
          "Foreheads touch. Eyes close at first.",
          "Breathe together: long, slow, belly breaths, synchronised.",
          "After five minutes, add circular breathing — inhaling as they exhale.",
          "Open the eyes for unbroken gaze. Stay.",
          "The posture can be held long past the point where the legs fall asleep — this is part of the transmission. Eventually, a quality of stillness arises that is unmistakable.",
        ],
        teaching: "The iconography of yab-yum (literally 'father-mother' in Tibetan) depicts enlightened consciousness as inseparable union. Held with presence, the posture itself delivers its own teaching.",
      },
      {
        title: "The Twining Creeper",
        lineage: "Vatsyayana · Kama Sutra",
        duration: "5–10 minutes",
        intention: "To reawaken the animal, playful, longing quality of embrace that long- term couples often forget.",
        setup: "Standing, in any room. Can be done fully clothed, spontaneously.",
        steps: [
          "One partner approaches the other, standing close.",
          "She clings to him as a creeper vine twines around a tree — one arm up around his neck, one around his waist, a leg slightly lifting.",
          "Her head bends gently down to his; she makes a small sound (the ancient text describes 'sut sut') — a sigh, a hum, a breath.",
          "He receives. He does not grab. He allows her to wrap.",
          "Hold for several long breaths. Then, unhurried, she climbs slightly higher as if reaching to kiss — the 'Climbing of a Tree' embrace.",
          "End in a still, full-body embrace, any duration.",
        ],
        teaching: "Vatsyayana specifies these embraces take place when the lover is standing — an intentional detail. The verticality is part of the charge.",
      },
      {
        title: "Spinal Rocking — Back to Back",
        lineage: "Yogi Bhajan · Kundalini · Venus Kriya",
        duration: "3 minutes",
        intention: "To establish joint rhythm, loosen the spine, and create nonverbal psychic attunement between partners.",
        setup: "Sit back-to-back on the floor in easy cross-legged pose. Spines perfectly aligned with each other, hips and shoulder blades in contact.",
        steps: [
          "Begin by synchronising breath — take three full breaths together, feeling each other's lungs expand.",
          "One partner inhales and leans back gently against the other, who exhales and folds forward.",
          "Reverse on the next breath — the one who folded now rises on the inhale; the other folds on the exhale.",
          "The rocking is slow, continuous, like a seesaw breathing together.",
          "Do not push or force. Let gravity do the work.",
          "Finish in perfect alignment, both spines tall, three breaths together in stillness.",
        ],
        teaching: "This kriya is usually the first contact practice in a Venus Kriya sequence. Three minutes of this resets the nervous system so that what follows can go much deeper.",
      },
      {
        title: "Daily Homecoming Ritual",
        lineage: "Integrated practice · Sacred Path tradition · Daily couples practice",
        duration: "5 minutes",
        intention: "To mark the transition between the day and the shared evening with a small, unmissable ritual that says: I have come home to you.",
        setup: "At the doorway, or the first moment of reunion at the end of the day.",
        steps: [
          "Stop. Put everything down — bag, phone, keys.",
          "Look at your partner. Simply see them.",
          "Hug. Hold until you feel them settle (usually 20–60 seconds).",
          "Whisper one sentence: 'I am glad to be home to you.'",
          "Breath together for three cycles.",
          "Then life can begin. Never skip this. Five minutes a day, every day, for years.",
        ],
        teaching: "This is the least technical and arguably most important practice in the book. Couples who anchor this into their daily life report that every other practice becomes easier, because the basic trust of coming home has been secured.",
      },
    ],
  },
  {
    id: "sacred-union-rituals",
    title: "Sacred Union Rituals",
    partLabel: "Part VIII",
    emotionalFrame: emotionalFrameByChapter["sacred-union-rituals"],
    rituals: [
      {
        title: "Conscious Lovemaking — The Barry Long Way",
        lineage: "Barry Long · Original Tantra · Making Love",
        duration: "60–120 minutes",
        intention: "To make love as a conscious act rather than an emotional release — so that what remains afterward is divine love itself, not momentary satisfaction.",
        setup: "A whole evening, with no other obligations. Clean sheets. The phones off. Alcohol minimal or absent.",
        steps: [
          "Begin with very long, slow contact — hours, if available. Not foreplay in the fast sense — a slow deepening of tenderness, with speech kept minimal.",
          "When union happens, it happens slowly, gently, with awareness held at the point of contact.",
          "Minimum movement. Stillness inside stillness. Long's instruction: feel the love, not the excitement.",
          "No goal of orgasm. No goal at all. Simply the presence of love in the body.",
          "If the man notices excitement rising toward ejaculation, he stops. The pause is not struggle — it is restoration of consciousness.",
          "End in stillness, sustained for as long as possible (see Ritual 32).",
        ],
        teaching: "Long's central claim was bold: conventional sex leaves behind an emotional residue that accumulates over years. Love made rightly, slowly, consciously, does the opposite — it clears that residue and restores a quality he called 'divine love' to the body itself.",
      },
      {
        title: "Slow Sex — Diana Richardson's Core Practice",
        lineage: "Diana Richardson · Slow Love · Making Love Retreats",
        duration: "45–90 minutes",
        intention: "To transform lovemaking from an accidental encounter driven by excitement into a conscious decision made in presence, awareness, and love.",
        setup: "Set aside an afternoon or evening. Meet in a warm, candlelit room. Approach this as one approaches meditation.",
        steps: [
          "Begin with a long Melting Hug (Ritual 20). Do not hurry.",
          "Move slowly to a side-by-side position in bed, fully present, not aroused yet — the opposite of fast-sex conditioning.",
          "Soft penetration: the man enters very gently, whether or not fully erect. Erection is not a prerequisite.",
          "Stay still inside. The subtle movements that happen without trying are the real ones.",
          "Breath slow and low. Eye contact soft. Body scans — quick mental tours through toes, belly, chest — return whenever the mind wanders.",
          "End whenever the body says so. Rest together in stillness for at least fifteen minutes before separating.",
        ],
        teaching: "Richardson's revolution is counterintuitive: coolness rather than heat; stillness rather than thrust; presence rather than performance. Couples who practise regularly report that slow sex feels more erotic than fast sex ever did.",
      },
      {
        title: "Microcosmic Orbit in Dual Cultivation",
        lineage: "Mantak Chia · Taoist Sexual Alchemy",
        duration: "30–60 minutes",
        intention: "To circulate sexual energy between two bodies through the Microcosmic Orbit — the shared channel that runs up the spine and down the front of each partner — creating a living loop that heals and nourishes both.",
        setup: "Requires familiarity with each partner's own Microcosmic Orbit practice. In union, seated in yab-yum or lying face to face.",
        steps: [
          "Begin seated in yab-yum, in gentle union. Tongue touches roof of mouth.",
          "Each partner activates their own orbit: energy rising up the back, down the front, back to the perineum.",
          "Now visualise the orbit connecting: your energy rises up your spine, passes into your partner's crown, descends their front, re-enters you at the perineum.",
          "Breath synchronises with this visualised loop — inhale as energy rises, exhale as it descends.",
          "Minimal physical motion. The alchemy is inward, not thrust-based.",
          "End with hands on each other's lower bellies, storing the cultivated energy in the lower tan tien.",
        ],
        teaching: "Chia teaches this as the doorway to the 'Valley Orgasm' — a state of prolonged shared bliss that does not depend on ejaculation. What is cultivated here becomes the couple's shared energetic reservoir.",
      },
      {
        title: "Riding the Wave of Bliss",
        lineage: "Margot Anand · SkyDancing Tantra",
        duration: "As long as the wave lasts",
        intention: "To cultivate and ride the wave of ecstatic energy, not as a peak to reach, but as a dimension to inhabit — the signature practice of SkyDancing Tantra.",
        setup: "Begin with Heart Salutation (19), Melting Hug (20), Tantric Massage (17). Then enter yab-yum (21) in gentle union.",
        steps: [
          "Hold the yab-yum posture with soft eye contact.",
          "Breath begins to synchronise, then to become circular: one inhales as the other exhales.",
          "As energy builds, visualise it rising through the seven chakras, each partner drawing it up together.",
          "Movement is subtle: a rocking of hips, a rolling of pelvises. Not thrusting — undulating.",
          "At any moment the wave may crest — orgasmic energy flooding both bodies without release. Stay in it. Let it wash through.",
          "When the wave subsides, rest in yab-yum for five to ten more minutes, in stillness.",
        ],
        teaching: "Anand calls this the 'core practice of the tantric path' — and notes that the Tibetan iconography of Yeshe Tsogyal and Padmasambhava depicts exactly this posture and exchange.",
      },
      {
        title: "Karezza — Union Without Discharge",
        lineage: "Classical Tantra · Osho lineage · Tantric Yoga",
        duration: "30 minutes to several hours",
        intention: "To remain in union for extended periods without the goal of climax — so that the boundary between pleasure and peace dissolves.",
        setup: "After long foreplay and energetic warming. Either lying face to face or in yab-yum.",
        steps: [
          "Enter union gently. Once joined, minimise movement.",
          "The focus is not sensation in the genitals but sensation in the whole body.",
          "Breathe long and slow. Eye contact soft. When arousal spikes, pause. When it settles, a new quality emerges — wider, warmer, more pervasive.",
          "This is not held as discipline; it is exploration. If orgasm happens, fine; but it is no longer the point.",
          "After extended union, a state of merging arises in which neither partner can say where they end and the other begins.",
          "Rest inside the state as long as it lasts.",
        ],
        teaching: "Osho called karezza 'the meeting of equals' — and noted that in deep union, for moments, 'the male becomes the female, and the female becomes the male.' Decades of Western teachers have confirmed this from direct experience.",
      },
    ],
  },
  {
    id: "emotional-clearing-authentic-relating",
    title: "Emotional Clearing & Authentic Relating",
    partLabel: "Part IX",
    emotionalFrame: emotionalFrameByChapter["emotional-clearing-authentic-relating"],
    rituals: [
      {
        title: "The Yes / No Exercise",
        lineage: "Jan Day · Living Tantra",
        duration: "20 minutes",
        intention: "To rebuild the foundation of intimacy: a clear yes that means yes, a clear no that means no, and a body that no longer betrays itself by saying one while feeling the other.",
        setup: "Sit facing each other. Take turns being the asker and the responder. Neutral topics to start ('may I touch your hand?').",
        steps: [
          "Partner A asks a simple question: 'May I touch your shoulder?'",
          "Partner B feels into the body. If the answer is yes, a clear 'yes' comes out. If no, a clear 'no.' If 'I don't know,' that is also a valid answer.",
          "Partner A respects the answer absolutely. No persuading, no disappointment.",
          "Reverse: Partner B asks; Partner A responds.",
          "Escalate the asks slowly over the twenty minutes: hand, shoulder, back, thigh — whatever feels meaningful to practice with.",
          "Finish with a reflection: what did you notice in your body when you said yes? When you said no?",
        ],
        teaching: "Day's experience: most couples have never done this. The body learns it is finally safe to say no — and from that safety, a much bigger yes becomes available. The exercise is the root of the whole Living Tantra approach.",
      },
      {
        title: "Vigyan Bhairava Emotional Yoga",
        lineage: "Daniel Odier · Kashmir Shaivism",
        duration: "20 minutes",
        intention: "To let emotion be felt in the body, in the present, as vibration — rather than narrated by the mind as story.",
        setup: "Either alone in shared space, or sitting close. Eyes closed.",
        steps: [
          "Bring to mind an emotion that has been present recently — sadness, anger, longing, fear.",
          "Drop the story. Do not narrate. Simply feel the physical sensation of the emotion — where it lives in the body, what it feels like, what shape it has.",
          "Stay with the sensation. No changing, no fixing.",
          "After ten minutes, the sensation will transform — not because you forced it to, but because felt sensation is vibration, and vibration moves.",
          "Open the eyes. Meet your partner. Share one sentence: 'I felt ___. Now I feel ___.'",
          "No response. Both have spoken. Sit in silence for one more minute.",
        ],
        teaching: "Odier's crucial teaching: the body consciousness of the Spanda practitioner is capable of living emotions through the body, not handing them to the mind to be rehearsed into the same old story.",
      },
      {
        title: "Parts Work Dialogue",
        lineage: "Jan Day · Living Tantra · drawing from IFS",
        duration: "30 minutes",
        intention: "To speak for the hidden, protective, scared, or angry parts of the self — so that they do not run the relationship from the shadows.",
        setup: "Sit side by side. Each partner will take turns speaking from different 'parts' of themselves.",
        steps: [
          "Partner A closes their eyes and senses into their body. What part wants to speak? ('There is an angry part. There is a scared little girl. There is a shut-down part.')",
          "They open their eyes and speak AS that part: 'I am the angry part of her. I am angry because…'",
          "Partner B listens without defending, offering only: 'I hear the angry part. I see it.'",
          "Partner A then shifts to another part: 'I am the scared part. I am scared that…'",
          "After ten minutes, roles reverse.",
          "Close with five minutes of quiet side-by-side sitting, no analysis.",
        ],
        teaching: "Day's method disarms the habitual drama of the couple-fight by making the hidden parts speakable. The argument is no longer between two adults but between a series of protective characters — all of whom finally feel seen.",
      },
      {
        title: "Sacred Intention Setting",
        lineage: "Charles & Caroline Muir · Source School of Tantra Yoga",
        duration: "10–15 minutes",
        intention: "Before any sacred spot ritual, before any extended lovemaking, to name what each partner brings and seeks — so that the encounter becomes conscious, not drift.",
        setup: "Sit facing each other, palms together or joined across the space between you.",
        steps: [
          "One partner begins: 'My intention for this time together is…' — they name three qualities or experiences they wish to bring and receive.",
          "The other listens, then mirrors back: 'I hear that you bring and seek…'",
          "The roles reverse.",
          "Both now name a shared intention together: 'Our intention for this time is…'",
          "Seal the intention: hands joined, heads slightly bowed, a single breath.",
          "Only then begin the ritual.",
        ],
        teaching: "The Muirs teach this as the opening of every Sacred Spot ceremony. The intention is the foundation: without it, the ritual is mere technique; with it, what happens becomes a rite of passage.",
      },
      {
        title: "Appreciation & Witness",
        lineage: "Jan Day · Deida (implicit) · Integrated neo-tantra",
        duration: "10 minutes",
        intention: "To end every day, every practice, every evening with a formalised appreciation — not because it is polite, but because it trains the heart to register the good that has actually happened.",
        setup: "Sit facing each other. Hands may be held or on own knees.",
        steps: [
          "Partner A: 'Three things I appreciate about you today are…' — and names three specific, small, true things.",
          "Partner B receives. No dismissing. No 'oh it was nothing.' Just: 'I receive that. Thank you.'",
          "Partner A: 'One thing I am grateful to have experienced today is…'",
          "Reverse roles: Partner B now speaks.",
          "Close in silence for a full minute.",
          "End with a Melting Hug of any length.",
        ],
        teaching: "Small, consistent appreciation is the invisible architecture of lasting intimacy. Couples who do this nightly find that over months, their field together feels fundamentally different.",
      },
      {
        title: "Embracing the Shadow Self",
        lineage: "Jan Day · Living Tantra",
        duration: "30 minutes",
        intention: "To name and welcome the disowned parts of oneself — jealousy, rage, neediness, coldness — so that they no longer sabotage the relationship from below consciousness.",
        setup: "Quiet, private space. Journal and pen optional.",
        steps: [
          "Each partner takes ten minutes alone. Write or reflect: 'The part of me I am most ashamed of is…'",
          "Come together. Partner A speaks: 'The shadow I am introducing you to is…' They name one quality, without defending it.",
          "Partner B receives with a single phrase: 'I see that in you. I welcome it.'",
          "Reverse roles.",
          "Both name one shadow quality they have projected onto the other: 'I see now that when I accused you of ___, I was meeting my own ___.'",
          "Close with a long Melting Hug.",
        ],
        teaching: "Day teaches that the shadow, welcomed, becomes an ally. The shadow denied becomes the ghost in every argument.",
      },
    ],
  },
];
